name: Deploy Database Innovatech
on:
  push:
    branches: [ deploy ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push DB Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/innovatech-db:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/innovatech-db:latest

      - name: Deploy via Proxy (Jump Host)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          proxy_host: ${{ secrets.EC2_PROXY_HOST }}
          proxy_username: ec2-user
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop front-app || true
            sudo docker rm front-app || true
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/innovatech-front:latest || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/innovatech-front:latest
            
            # MAGIA: Mapeamos localhost directamente a la IP del Backend
            sudo docker run -d --name front-app -p 80:5000 \
              --add-host=localhost:10.0.2.62 \
              ${{ secrets.DOCKER_USERNAME }}/innovatech-front:latest